### PR TITLE
fix(application.properties): increase default http max-body-size

### LINKED ISSUE #83: Quarkus sets a small maximum upload size
https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.limits.max-body-size

This causes the maximum default uploadable .jfr filesize to be limited to 10MB, which is quite small. A larger default should be set in `application.properties`.

https://github.com/quarkusio/quarkus/issues/10079

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #83

### CODE REVIEW

**Comment by jiekang** [comment]
Can the project documentation that describes this API mention this limitation and provide the alternate command for larger files (oc cp/rsync)?

**Comment by andrewazores** [comment]
> Can the project documentation that describes this API mention this limitation and provide the alternate command for larger files (oc cp/rsync)?

Sure, will do. From my understanding the workaround would need to first be an `oc cp` to put the file into the datasource's storage, and then a `POST /set` to trigger the datasource loading the newly-added file's contents. Does that seem right?

**Comment by jiekang** [comment]
> > Can the project documentation that describes this API mention this limitation and provide the alternate command for larger files (oc cp/rsync)?
> 
> Sure, will do. From my understanding the workaround would need to first be an `oc cp` to put the file into the datasource's storage, and then a `POST /set` to trigger the datasource loading the newly-added file's contents. Does that seem right?

I think the `/upload` API can mention the size limitation and the workaround, then the `/load` API can mention the limitation and reference the documentation before in some manner.

**Comment by jiekang** [comment]
Also I don't mind the size limitation being bumped to 10G

**Comment by andrewazores** [comment]
I have bumped the default configuration up to 10GB in `application.properties` and documented the limitation and configuration in the README.

**Review by jiekang — APPROVED** [review]

**Review by ebaron — APPROVED** [review]
Thanks for noticing and fix this!

**Pull request merged**
