### PR TITLE
ci(push): fix container stream name

### PR DESCRIPTION
**Pull request by andrewazores**
Related to #147

Should fix job failure: https://github.com/cryostatio/jfr-datasource/pull/148#issuecomment-1315831378

### CODE REVIEW

**Review by ebaron — APPROVED** [review]

**Comment by andrewazores** [comment]
Here's the next try: https://github.com/cryostatio/jfr-datasource/actions/runs/3474495798

**Comment by andrewazores** [comment]
Failed this time due to unauthorized access to the Quay API. Not sure why exactly - the secret should be org-wide and visible to all public repos.

**Comment by andrewazores** [comment]
Here's a similar job on the main Cryostat repo for comparison. It looks like it was trying to do the same thing:

https://github.com/cryostatio/cryostat/actions/runs/3473887722/jobs/5806774300

so I guess the problem is in fact with the secret, probably.

**Comment by andrewazores** [comment]
@ebaron was the secret that you created somehow scoped to a specific GitHub repo or Quay repo?

**Comment by andrewazores** [comment]
Ah I see a setting on the Quay robot account for the repos it has access to. I just updated it and will retry the job.

**Comment by andrewazores** [comment]
https://github.com/cryostatio/jfr-datasource/actions/runs/3474495798

**Comment by andrewazores** [comment]
Works now.

**Pull request merged**
